version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - backend
      
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:300
    volumes:
      - ./frontend:/app
    networks:
      - backend
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    volumes:
      - ./api:/app
    networks:
      - backend

  db:
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend


networks:
  backend:

volumes:
  db-data:
